import yaml
import json
import sys
import os

def load_dify_dsl(filepath):
    """Loads and parses the Dify YAML DSL."""
    with open(filepath, 'r') as f:
        return yaml.safe_load(f)

def extract_variables(nodes):
    """Finds the 'start' node and extracts input variable definitions."""
    start_node = next((n for n in nodes if n.get('data', {}).get('type') == 'start'), None)
    if not start_node:
        return []
    
    return [v.get('variable') for v in start_node['data'].get('variables', [])]

def extract_conditions(nodes):
    """Extracts simple routing conditions from 'if-else' nodes."""
    conditions = []
    
    for node in nodes:
        if node.get('data', {}).get('type') == 'if-else':
            cases = node['data'].get('cases', [])
            for case in cases:
                for cond in case.get('conditions', []):
                    # In Dify, variable_selector is often [node_id, var_name]
                    var_name = cond['variable_selector'][-1] if 'variable_selector' in cond else None
                    op = cond.get('comparison_operator', '==')
                    val = cond.get('value', '0')
                    
                    if var_name:
                        conditions.append({
                            "variable": var_name,
                            "operator": op,
                            "value": val
                        })
    return conditions

def generate_rust_code(variables, conditions):
    """Generates the lib.rs string for WASM compilation based on extracted logic."""
    
    if not variables:
        variables = ['close', 'rsi'] # Fallback
        
    num_vars = len(variables)
    
    # 1. Build the variable extraction block
    var_extraction = ""
    for idx, var in enumerate(variables):
        var_extraction += f"        let {var} = inputs[base_idx + {idx}];\n"
        
    # 2. Build the logic block based on Dify conditions
    # For MVP, we will assume a simple single BUY condition parsed from the first "if"
    
    logic_block = ""
    if conditions:
        # e.g., if rsi < 30
        cond = conditions[0]
        # In Rust, float comparisons need valid syntax. Dify passes strings for values.
        try:
            val_f64 = float(cond['value'])
            val_str = f"{val_f64:.1f}"
        except ValueError:
            val_str = cond['value']
            
        logic_block = f"""
        if {cond['variable']} {cond['operator']} {val_str} {{
            outputs[i] = 1; // True condition (BUY)
        }} else {{
            outputs[i] = 0; // False condition (HOLD)
        }}"""
    else:
        logic_block = "        outputs[i] = 0; // Default HOLD"

    # 3. Assemble the final Rust template
    rust_template = f"""#![no_std]
#![allow(clippy::missing_safety_doc)]
#![allow(unused_variables)]

// AUTO-GENERATED BY IMAGINOS WASM TRANSPILER
// Based on Dify Visual Workflow

#[no_mangle]
pub unsafe extern "C" fn process_batch(
    input_ptr: *const f64,
    output_ptr: *mut i32,
    num_candles: usize,
) {{
    let inputs = core::slice::from_raw_parts(input_ptr, num_candles * {num_vars});
    let outputs = core::slice::from_raw_parts_mut(output_ptr, num_candles);

    for i in 0..num_candles {{
        let base_idx = i * {num_vars};
        
{var_extraction}
{logic_block}
    }}
}}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {{
    loop {{}}
}}
"""
    return rust_template

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Compile Dify DSL to Rust WASM code.")
    parser.add_argument("dsl_file", help="Path to the Dify YAML file")
    parser.add_argument("output_file", help="Path to write the lib.rs file")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.dsl_file):
        print(f"Error: Could not find DSL file at {args.dsl_file}")
        sys.exit(1)
        
    print(f"Loading Dify DSL from {args.dsl_file}...")
    dsl = load_dify_dsl(args.dsl_file)
    nodes = dsl.get('workflow', {}).get('graph', {}).get('nodes', [])
    
    print("Extracting variables from Start Node...")
    variables = extract_variables(nodes)
    print(f"Found variables: {variables}")
    
    print("Extracting logic from If/Else Nodes...")
    conditions = extract_conditions(nodes)
    print(f"Found conditions: {conditions}")
    
    print("Generating optimized Rust code...")
    rust_code = generate_rust_code(variables, conditions)
    
    with open(args.output_file, 'w') as f:
        f.write(rust_code)
        
    print(f"Successfully generated Rust WASM source at {args.output_file}")
    print("Ready for 'cargo build --target wasm32-unknown-unknown --release'")

if __name__ == "__main__":
    main()
