openapi: 3.0.0
info:
  title: Latinos Financial Tools
  version: 1.0.0
  description: Native Financial Indicators (RSI, MACD, MA) for Dify visual strategy building.
servers:
  - url: https://apilatinos.paulovila.org
paths:
  /api/dify/tools/rsi:
    post:
      operationId: calculate_rsi
      summary: Calculate RSI
      description: Calculates the Relative Strength Index (RSI).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - close_prices
              properties:
                close_prices:
                  type: array
                  items:
                    type: number
                  description: Array of historical close prices.
                period:
                  type: integer
                  description: Calculation period.
                  default: 14
      responses:
        "200":
          description: OK
  /api/dify/tools/macd:
    post:
      operationId: calculate_macd
      summary: Calculate MACD
      description: Calculates the Moving Average Convergence Divergence.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - close_prices
              properties:
                close_prices:
                  type: array
                  items:
                    type: number
                fast_period:
                  type: integer
                  default: 12
                slow_period:
                  type: integer
                  default: 26
                signal_period:
                  type: integer
                  default: 9
      responses:
        "200":
          description: OK
  /api/dify/tools/ma:
    post:
      operationId: calculate_ma
      summary: Calculate Moving Average
      description: Calculates SMA or EMA.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - close_prices
              properties:
                close_prices:
                  type: array
                  items:
                    type: number
                period:
                  type: integer
                  default: 14
                type:
                  type: string
                  default: sma
      responses:
        "200":
          description: OK
