//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_bots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: String,
    pub is_wasm: bool,
    pub wasm_hash: Option<String>,
    pub live_trading: bool,
    pub dify_app_id: Option<String>,
    pub tags: Option<Json>,
    pub signal_manifest: Option<Json>,
    #[sea_orm(column_type = "Float", nullable)]
    pub tp_percent: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub sl_percent: Option<f32>,
    pub live_metrics: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub manifest_version: Option<i32>,
    pub manifest_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub manifest_migration_note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::latinos_backtests::Entity")]
    LatinosBacktests,
    #[sea_orm(has_many = "super::latinos_signals::Entity")]
    LatinosSignals,
    #[sea_orm(has_many = "super::latinos_trades::Entity")]
    LatinosTrades,
    #[sea_orm(
        belongs_to = "super::latinos_users::Entity",
        from = "Column::OwnerId",
        to = "super::latinos_users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LatinosUsers,
}

impl Related<super::latinos_backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosBacktests.def()
    }
}

impl Related<super::latinos_signals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosSignals.def()
    }
}

impl Related<super::latinos_trades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosTrades.def()
    }
}

impl Related<super::latinos_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosUsers.def()
    }
}
