//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_opportunities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub research_id: i32,
    pub score: i32,
    #[sea_orm(column_type = "Float")]
    pub confidence_score: f32,
    pub stance: String,
    #[sea_orm(column_type = "Text")]
    pub thesis: String,
    pub catalysts: Json,
    pub risks: Json,
    pub key_metrics: Json,
    pub disqualifier_flags: Json,
    pub catalyst_windows: Json,
    pub research_date: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub visibility_scope: String,
    pub visibility_key: Option<String>,
    pub owner_id: Option<i32>,
    pub is_global: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::latinos_users::Entity",
        from = "Column::OwnerId",
        to = "super::latinos_users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LatinosUsers,
}

impl Related<super::latinos_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosUsers.def()
    }
}
