//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_trades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i32>,
    pub bot_id: Option<i32>,
    pub symbol: String,
    pub side: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    pub status: String,
    pub broker: Option<String>,
    pub broker_order_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pnl: Option<f64>,
    pub timestamp: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::latinos_bots::Entity",
        from = "Column::BotId",
        to = "super::latinos_bots::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LatinosBots,
    #[sea_orm(
        belongs_to = "super::latinos_users::Entity",
        from = "Column::UserId",
        to = "super::latinos_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LatinosUsers,
}

impl Related<super::latinos_bots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosBots.def()
    }
}

impl Related<super::latinos_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosUsers.def()
    }
}
