//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub role: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::latinos_bots::Entity")]
    LatinosBots,
    #[sea_orm(has_many = "super::latinos_broker_connections::Entity")]
    LatinosBrokerConnections,
    #[sea_orm(has_many = "super::latinos_opportunities::Entity")]
    LatinosOpportunities,
    #[sea_orm(has_many = "super::latinos_trades::Entity")]
    LatinosTrades,
}

impl Related<super::latinos_bots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosBots.def()
    }
}

impl Related<super::latinos_broker_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosBrokerConnections.def()
    }
}

impl Related<super::latinos_opportunities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosOpportunities.def()
    }
}

impl Related<super::latinos_trades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosTrades.def()
    }
}
