//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_market_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub symbol: String,
    pub interval: String,
    #[sea_orm(column_type = "Double")]
    pub open: f64,
    #[sea_orm(column_type = "Double")]
    pub high: f64,
    #[sea_orm(column_type = "Double")]
    pub low: f64,
    #[sea_orm(column_type = "Double")]
    pub close: f64,
    #[sea_orm(column_type = "Double")]
    pub volume: f64,
    pub ts: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
