//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_signals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bot_id: Option<i32>,
    pub r#type: String,
    pub name: Option<String>,
    pub payload: Option<Json>,
    pub emitted_at: DateTimeWithTimeZone,
    pub mode: String,
    pub delivery_status: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::latinos_bots::Entity",
        from = "Column::BotId",
        to = "super::latinos_bots::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LatinosBots,
    #[sea_orm(has_many = "super::latinos_formula_versions::Entity")]
    LatinosFormulaVersions,
}

impl Related<super::latinos_bots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosBots.def()
    }
}

impl Related<super::latinos_formula_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosFormulaVersions.def()
    }
}
