//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_broker_connections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub broker: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub credentials_encrypted: Option<String>,
    pub status: String,
    pub last_synced_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::latinos_users::Entity",
        from = "Column::UserId",
        to = "super::latinos_users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LatinosUsers,
}

impl Related<super::latinos_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosUsers.def()
    }
}
