//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "latinos_formula_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub signal_id: Option<i32>,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub language: String,
    pub sandbox_result: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::latinos_signals::Entity",
        from = "Column::SignalId",
        to = "super::latinos_signals::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LatinosSignals,
}

impl Related<super::latinos_signals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LatinosSignals.def()
    }
}
