//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod latinos_backtests;
pub mod latinos_bots;
pub mod latinos_broker_connections;
pub mod latinos_formula_versions;
pub mod latinos_market_data;
pub mod latinos_opportunities;
pub mod latinos_signals;
pub mod latinos_trades;
pub mod latinos_users;
pub mod stock_research;
