//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::latinos_backtests::Entity as LatinosBacktests;
pub use super::latinos_bots::Entity as LatinosBots;
pub use super::latinos_broker_connections::Entity as LatinosBrokerConnections;
pub use super::latinos_formula_versions::Entity as LatinosFormulaVersions;
pub use super::latinos_market_data::Entity as LatinosMarketData;
pub use super::latinos_opportunities::Entity as LatinosOpportunities;
pub use super::latinos_signals::Entity as LatinosSignals;
pub use super::latinos_trades::Entity as LatinosTrades;
pub use super::latinos_users::Entity as LatinosUsers;
pub use super::stock_research::Entity as StockResearch;
