//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_research")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub owner_email: String,
    pub source: String,
    pub bot_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub raw_data: Json,
    #[sea_orm(column_type = "Text")]
    pub analysis_summary: String,
    pub research_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
