// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/style-guide": {
    params: {};
  };
  "/credits": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sitemap.xml" | "/style-guide" | "/credits" | "/robots.txt" | "/_image/*";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[style-guide]._index.tsx": {
    id: "routes/[style-guide]._index";
    page: "/style-guide";
  };
  "routes/[credits]._index.tsx": {
    id: "routes/[credits]._index";
    page: "/credits";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[style-guide]._index": typeof import("./app/routes/[style-guide]._index.tsx");
  "routes/[credits]._index": typeof import("./app/routes/[credits]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[_image].$": typeof import("./app/routes/[_image].$.ts");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};